xrbd -load "$XDG_CONFIG_HOME/X11/xresources"

feh --bg-max --randomize "$HOME"/Pictures/wallpapers/* &

picom --experimental-backends -b >/dev/null 2>&1 || { echo "no picom available"; sleep 2 }

exec dwm 2> /tmp/dwm.log
